use crate::core::errors::BitOSDTResult;
use serde::{Deserialize, Serialize};
use tracing::info;

/// Domain join script generator
pub struct DomainJoinGenerator;

/// Domain join configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DomainJoinConfig {
    /// Domain name (e.g., "corp.contoso.com")
    pub domain_name: String,
    /// Domain admin username
    pub username: String,
    /// Domain admin password (will be handled securely)
    pub password: String,
    /// Organizational Unit path (optional)
    pub ou_path: Option<String>,
    /// Retry count on failure
    pub retry_count: u32,
    /// Delay between retries (seconds)
    pub retry_delay_seconds: u32,
    /// Fallback to workgroup if domain join fails
    pub fallback_to_workgroup: bool,
    /// Workgroup name for fallback
    pub fallback_workgroup: String,
    /// Reboot after join
    pub reboot_after_join: bool,
    /// Log file path
    pub log_path: String,
}

impl Default for DomainJoinConfig {
    fn default() -> Self {
        Self {
            domain_name: String::new(),
            username: String::new(),
            password: String::new(),
            ou_path: None,
            retry_count: 3,
            retry_delay_seconds: 30,
            fallback_to_workgroup: true,
            fallback_workgroup: "WORKGROUP".to_string(),
            reboot_after_join: false,
            log_path: "C:\\BitOSDT\\Logs\\domain-join.log".to_string(),
        }
    }
}

impl DomainJoinGenerator {
    /// Generate PowerShell script for domain join
    pub fn generate_script(config: &DomainJoinConfig) -> BitOSDTResult<String> {
        info!("Generating domain join script for: {}", config.domain_name);

        let _ou_param = config
            .ou_path
            .as_ref()
            .map(|ou| format!("-OUPath \"{}\"", ou))
            .unwrap_or_default();

        let script = format!(
            r#"# BitOSDT Domain Join Script
# Generated by BitOSDT 2.0
# ================================================

$ErrorActionPreference = "Continue"
$LogPath = "{log_path}"

# Configuration
$DomainName = "{domain_name}"
$Username = "{username}"
$Password = ConvertTo-SecureString "{password}" -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential($Username, $Password)
$OUPath = "{ou_path}"
$MaxRetries = {retry_count}
$RetryDelay = {retry_delay}
$FallbackToWorkgroup = ${fallback_workgroup_bool}
$FallbackWorkgroup = "{fallback_workgroup}"
$RebootAfterJoin = ${reboot_after_join}

# Create log directory
$logDir = Split-Path $LogPath -Parent
if (-not (Test-Path $logDir)) {{
    New-Item -Path $logDir -ItemType Directory -Force | Out-Null
}}

function Write-Log {{
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logLine = "$timestamp [$Level] $Message"
    $logLine | Out-File -Append $LogPath
    
    switch ($Level) {{
        "ERROR" {{ Write-Host $logLine -ForegroundColor Red }}
        "WARNING" {{ Write-Host $logLine -ForegroundColor Yellow }}
        "SUCCESS" {{ Write-Host $logLine -ForegroundColor Green }}
        default {{ Write-Host $logLine }}
    }}
}}

function Test-DomainReachable {{
    param([string]$Domain)
    try {{
        $result = [System.Net.Dns]::GetHostAddresses($Domain)
        return $result.Count -gt 0
    }} catch {{
        return $false
    }}
}}

function Join-DomainWithRetry {{
    param(
        [string]$Domain,
        [PSCredential]$Credential,
        [string]$OU,
        [int]$MaxRetries,
        [int]$RetryDelay
    )
    
    for ($attempt = 1; $attempt -le $MaxRetries; $attempt++) {{
        Write-Log "Domain join attempt $attempt of $MaxRetries..."
        
        # Check domain reachability
        if (-not (Test-DomainReachable -Domain $Domain)) {{
            Write-Log "Domain $Domain is not reachable" "WARNING"
            if ($attempt -lt $MaxRetries) {{
                Write-Log "Waiting $RetryDelay seconds before retry..."
                Start-Sleep -Seconds $RetryDelay
                continue
            }}
            return $false
        }}
        
        try {{
            $joinParams = @{{
                DomainName = $Domain
                Credential = $Credential
                Force = $true
                ErrorAction = 'Stop'
            }}
            
            if (-not [string]::IsNullOrEmpty($OU)) {{
                $joinParams['OUPath'] = $OU
            }}
            
            Add-Computer @joinParams
            Write-Log "Successfully joined domain: $Domain" "SUCCESS"
            return $true
        }} catch {{
            Write-Log "Domain join failed: $_" "ERROR"
            
            if ($attempt -lt $MaxRetries) {{
                Write-Log "Waiting $RetryDelay seconds before retry..."
                Start-Sleep -Seconds $RetryDelay
            }}
        }}
    }}
    
    return $false
}}

# Main execution
Write-Log "Starting domain join process..."
Write-Log "Target domain: $DomainName"
Write-Log "Using credentials for: $Username"

# Check if already joined to this domain
$currentDomain = (Get-WmiObject Win32_ComputerSystem).Domain
if ($currentDomain -eq $DomainName) {{
    Write-Log "Computer is already joined to $DomainName" "SUCCESS"
    exit 0
}}

# Attempt domain join
$joinSuccess = Join-DomainWithRetry -Domain $DomainName -Credential $Credential -OU $OUPath -MaxRetries $MaxRetries -RetryDelay $RetryDelay

if ($joinSuccess) {{
    Write-Log "Domain join completed successfully" "SUCCESS"
    
    if ($RebootAfterJoin) {{
        Write-Log "Rebooting in 60 seconds..."
        shutdown /r /t 60 /c "BitOSDT: Rebooting after domain join"
    }}
    
    exit 0
}} else {{
    Write-Log "All domain join attempts failed" "ERROR"
    
    if ($FallbackToWorkgroup) {{
        Write-Log "Falling back to workgroup: $FallbackWorkgroup" "WARNING"
        try {{
            Add-Computer -WorkgroupName $FallbackWorkgroup -Force
            Write-Log "Joined workgroup: $FallbackWorkgroup" "SUCCESS"
            exit 0
        }} catch {{
            Write-Log "Failed to join workgroup: $_" "ERROR"
        }}
    }}
    
    exit 1
}}
"#,
            log_path = config.log_path,
            domain_name = config.domain_name,
            username = config.username,
            password = config.password, // In production, use secure methods
            ou_path = config.ou_path.as_deref().unwrap_or(""),
            retry_count = config.retry_count,
            retry_delay = config.retry_delay_seconds,
            fallback_workgroup_bool = if config.fallback_to_workgroup {
                "true"
            } else {
                "false"
            },
            fallback_workgroup = config.fallback_workgroup,
            reboot_after_join = if config.reboot_after_join {
                "true"
            } else {
                "false"
            }
        );

        Ok(script)
    }

    /// Generate a simple one-liner for domain join (for unattend.xml alternative)
    pub fn generate_simple_command(config: &DomainJoinConfig) -> String {
        let ou_param = config
            .ou_path
            .as_ref()
            .map(|ou| format!(" -OUPath '{}'", ou))
            .unwrap_or_default();

        format!(
            r#"$secPwd = ConvertTo-SecureString '{}' -AsPlainText -Force; $cred = New-Object PSCredential('{}', $secPwd); Add-Computer -DomainName '{}'{} -Credential $cred -Force"#,
            config.password, config.username, config.domain_name, ou_param
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_domain_join_script() {
        let config = DomainJoinConfig {
            domain_name: "corp.contoso.com".to_string(),
            username: "CORP\\admin".to_string(),
            password: "P@ssw0rd".to_string(),
            ou_path: Some("OU=Computers,DC=corp,DC=contoso,DC=com".to_string()),
            ..Default::default()
        };

        let script = DomainJoinGenerator::generate_script(&config).unwrap();

        assert!(script.contains("corp.contoso.com"));
        assert!(script.contains("Add-Computer"));
        assert!(script.contains("OU=Computers"));
    }

    #[test]
    fn test_generate_simple_command() {
        let config = DomainJoinConfig {
            domain_name: "test.local".to_string(),
            username: "admin".to_string(),
            password: "secret".to_string(),
            ou_path: None,
            ..Default::default()
        };

        let cmd = DomainJoinGenerator::generate_simple_command(&config);

        assert!(cmd.contains("test.local"));
        assert!(cmd.contains("Add-Computer"));
    }
}
