use crate::core::errors::BitOSDTResult;
use serde::{Deserialize, Serialize};
use tracing::info;

/// Generic script generator for custom scripts
pub struct ScriptGenerator;

/// Custom script configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomScript {
    /// Script name
    pub name: String,
    /// Script content
    pub content: String,
    /// Script type
    pub script_type: ScriptType,
    /// Run as administrator
    pub run_as_admin: bool,
    /// Continue on error
    pub continue_on_error: bool,
    /// Timeout in seconds (0 = no timeout)
    pub timeout_seconds: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ScriptType {
    PowerShell,
    Batch,
}

impl ScriptGenerator {
    /// Generate a wrapper script that executes custom scripts with logging
    pub fn generate_wrapper_script(
        scripts: &[CustomScript],
        log_path: &str,
    ) -> BitOSDTResult<String> {
        info!(
            "Generating wrapper script for {} custom scripts",
            scripts.len()
        );

        let mut wrapper = format!(
            r#"# BitOSDT Custom Script Executor
# Generated by BitOSDT 2.0
# ================================================

$LogPath = "{log_path}"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Create log directory
$logDir = Split-Path $LogPath -Parent
if (-not (Test-Path $logDir)) {{
    New-Item -Path $logDir -ItemType Directory -Force | Out-Null
}}

function Write-Log {{
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logLine = "$timestamp [$Level] $Message"
    $logLine | Out-File -Append $LogPath
    
    switch ($Level) {{
        "ERROR" {{ Write-Host $logLine -ForegroundColor Red }}
        "WARNING" {{ Write-Host $logLine -ForegroundColor Yellow }}
        "SUCCESS" {{ Write-Host $logLine -ForegroundColor Green }}
        default {{ Write-Host $logLine }}
    }}
}}

function Invoke-ScriptWithTimeout {{
    param(
        [string]$ScriptPath,
        [int]$Timeout = 0,
        [bool]$ContinueOnError = $true
    )
    
    try {{
        if ($Timeout -gt 0) {{
            $job = Start-Job -ScriptBlock {{
                param($path)
                & $path
            }} -ArgumentList $ScriptPath
            
            $completed = Wait-Job $job -Timeout $Timeout
            
            if ($completed) {{
                Receive-Job $job
                return $true
            }} else {{
                Stop-Job $job
                Remove-Job $job -Force
                Write-Log "Script timed out after $Timeout seconds" "ERROR"
                return $ContinueOnError
            }}
        }} else {{
            & $ScriptPath
            return $true
        }}
    }} catch {{
        Write-Log "Script error: $_" "ERROR"
        return $ContinueOnError
    }}
}}

Write-Log "Starting custom script execution..."
$scriptsExecuted = 0
$scriptsFailed = 0

"#,
            log_path = log_path
        );

        // Add execution for each script
        for (index, script) in scripts.iter().enumerate() {
            let script_filename = match script.script_type {
                ScriptType::PowerShell => format!(
                    "script_{:02}_{}.ps1",
                    index,
                    sanitize_filename(&script.name)
                ),
                ScriptType::Batch => format!(
                    "script_{:02}_{}.cmd",
                    index,
                    sanitize_filename(&script.name)
                ),
            };

            wrapper.push_str(&format!(
                r#"
# Script: {name}
Write-Log "Executing: {name}"
$scriptPath = Join-Path $ScriptDir "{filename}"

if (Test-Path $scriptPath) {{
    $success = Invoke-ScriptWithTimeout -ScriptPath $scriptPath -Timeout {timeout} -ContinueOnError ${continue_on_error}
    
    if ($success) {{
        Write-Log "{name} completed successfully" "SUCCESS"
        $scriptsExecuted++
    }} else {{
        Write-Log "{name} failed" "ERROR"
        $scriptsFailed++
        {error_handling}
    }}
}} else {{
    Write-Log "Script not found: $scriptPath" "ERROR"
    $scriptsFailed++
}}

"#,
                name = script.name,
                filename = script_filename,
                timeout = script.timeout_seconds,
                continue_on_error = if script.continue_on_error { "true" } else { "false" },
                error_handling = if script.continue_on_error {
                    "# Continue on error"
                } else {
                    "Write-Log \"Stopping due to error\"; exit 1"
                }
            ));
        }

        wrapper.push_str(
            r#"
# Summary
Write-Log "Custom script execution completed"
Write-Log "Scripts executed: $scriptsExecuted"
Write-Log "Scripts failed: $scriptsFailed"

if ($scriptsFailed -gt 0) {
    exit 1
} else {
    exit 0
}
"#,
        );

        Ok(wrapper)
    }

    /// Generate a simple PowerShell script wrapper
    pub fn wrap_powershell_script(content: &str, run_as_admin: bool) -> String {
        let admin_check = if run_as_admin {
            r#"
# Require administrator
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error "This script requires administrator privileges"
    exit 1
}
"#
        } else {
            ""
        };

        format!(
            r#"# Custom PowerShell Script
# Wrapped by BitOSDT 2.0

$ErrorActionPreference = "Stop"
{admin_check}
{content}
"#,
            admin_check = admin_check,
            content = content
        )
    }

    /// Generate SetupComplete.cmd content
    pub fn generate_setup_complete_cmd(_scripts_dir: &str, log_path: &str) -> String {
        format!(
            r#"@echo off
REM BitOSDT SetupComplete.cmd
REM This script runs on first boot after Windows installation

set "LOGFILE={log_path}"
for %%I in ("%LOGFILE%") do set "LOGDIR=%%~dpI"
if not exist "%LOGDIR%" (
    mkdir "%LOGDIR%" >nul 2>&1
)
if not exist "%LOGDIR%" (
    set "LOGFILE=%WINDIR%\Temp\bitosdt-setup-complete.log"
)

echo %DATE% %TIME% - BitOSDT SetupComplete starting >> %LOGFILE%

REM Run PowerShell tasks
echo %DATE% %TIME% - Running PowerShell tasks >> %LOGFILE%
powershell.exe -ExecutionPolicy Bypass -File "%~dp0task-runner.ps1" >> %LOGFILE% 2>&1

REM Create completion flag
echo %DATE% %TIME% - Creating completion flag >> %LOGFILE%
echo COMPLETE > "%~dp0setup-complete.flag"

echo %DATE% %TIME% - BitOSDT SetupComplete finished >> %LOGFILE%
"#,
            log_path = log_path
        )
    }

    /// Generate OOBESystem runonce registry commands
    pub fn generate_runonce_reg(command: &str, name: &str) -> String {
        format!(
            r#"Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce]
"{name}"="cmd /c \"{command}\""
"#,
            name = name,
            command = command.replace("\\", "\\\\").replace("\"", "\\\"")
        )
    }
}

fn sanitize_filename(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_wrapper_script() {
        let scripts = vec![CustomScript {
            name: "Test Script".to_string(),
            content: "Write-Host 'Hello'".to_string(),
            script_type: ScriptType::PowerShell,
            run_as_admin: false,
            continue_on_error: true,
            timeout_seconds: 300,
        }];

        let wrapper =
            ScriptGenerator::generate_wrapper_script(&scripts, "C:\\Logs\\test.log").unwrap();

        assert!(wrapper.contains("Test Script"));
        assert!(wrapper.contains("Invoke-ScriptWithTimeout"));
    }

    #[test]
    fn test_wrap_powershell_script() {
        let content = "Write-Host 'Test'";
        let wrapped = ScriptGenerator::wrap_powershell_script(content, true);

        assert!(wrapped.contains("Write-Host 'Test'"));
        assert!(wrapped.contains("administrator"));
    }

    #[test]
    fn test_setup_complete_cmd() {
        let cmd = ScriptGenerator::generate_setup_complete_cmd(
            "C:\\BitOSDT\\Tasks",
            "C:\\BitOSDT\\Logs\\setup.log",
        );

        assert!(cmd.contains("for %%I in (\"%LOGFILE%\") do set \"LOGDIR=%%~dpI\""));
        assert!(cmd.contains("mkdir \"%LOGDIR%\" >nul 2>&1"));
        assert!(cmd.contains("set \"LOGFILE=%WINDIR%\\Temp\\bitosdt-setup-complete.log\""));
        assert!(cmd.contains("%~dp0task-runner.ps1"));
        assert!(cmd.contains("setup-complete.flag"));
    }

    #[test]
    fn test_sanitize_filename() {
        assert_eq!(sanitize_filename("My Script!"), "My_Script_");
        assert_eq!(sanitize_filename("test-script_01"), "test-script_01");
    }
}
