use crate::core::errors::BitOSDTResult;
use serde::{Deserialize, Serialize};
use tracing::info;

/// User account creator script generator
pub struct UserCreatorGenerator;

/// User account configuration
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct UserAccountConfig {
    /// Username
    pub username: String,
    /// Password
    pub password: String,
    /// Full name / display name
    pub full_name: Option<String>,
    /// Description
    pub description: Option<String>,
    /// Add to Administrators group
    pub is_admin: bool,
    /// Password never expires
    pub password_never_expires: bool,
    /// User cannot change password
    pub user_cannot_change_password: bool,
    /// Account is disabled
    pub account_disabled: bool,
    /// Require password change at next logon
    pub require_password_change: bool,
}

/// Multiple users configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsersConfig {
    /// List of users to create
    pub users: Vec<UserAccountConfig>,
    /// Log file path
    pub log_path: String,
    /// Continue on error
    pub continue_on_error: bool,
}

impl Default for UsersConfig {
    fn default() -> Self {
        Self {
            users: Vec::new(),
            log_path: "C:\\BitOSDT\\Logs\\user-creation.log".to_string(),
            continue_on_error: true,
        }
    }
}

impl UserCreatorGenerator {
    /// Generate PowerShell script to create users
    pub fn generate_script(config: &UsersConfig) -> BitOSDTResult<String> {
        info!(
            "Generating user creation script for {} users",
            config.users.len()
        );

        let mut script = format!(
            r#"# BitOSDT User Creation Script
# Generated by BitOSDT 2.0
# ================================================

$ErrorActionPreference = "{error_action}"
$LogPath = "{log_path}"

# Create log directory
$logDir = Split-Path $LogPath -Parent
if (-not (Test-Path $logDir)) {{
    New-Item -Path $logDir -ItemType Directory -Force | Out-Null
}}

function Write-Log {{
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logLine = "$timestamp [$Level] $Message"
    $logLine | Out-File -Append $LogPath
    
    switch ($Level) {{
        "ERROR" {{ Write-Host $logLine -ForegroundColor Red }}
        "WARNING" {{ Write-Host $logLine -ForegroundColor Yellow }}
        "SUCCESS" {{ Write-Host $logLine -ForegroundColor Green }}
        default {{ Write-Host $logLine }}
    }}
}}

Write-Log "Starting user account creation..."

"#,
            error_action = if config.continue_on_error {
                "Continue"
            } else {
                "Stop"
            },
            log_path = config.log_path
        );

        for user in &config.users {
            script.push_str(&Self::generate_user_creation(user));
        }

        script.push_str(
            r#"
Write-Log "User account creation completed." "SUCCESS"
exit 0
"#,
        );

        Ok(script)
    }

    fn generate_user_creation(user: &UserAccountConfig) -> String {
        let full_name = user
            .full_name
            .as_ref()
            .map(|n| format!("-FullName \"{}\"", n))
            .unwrap_or_default();

        let description = user
            .description
            .as_ref()
            .map(|d| format!("-Description \"{}\"", d))
            .unwrap_or_default();

        format!(
            r#"
# Create user: {username}
Write-Log "Creating user account: {username}"

try {{
    # Check if user already exists
    $existingUser = Get-LocalUser -Name "{username}" -ErrorAction SilentlyContinue
    
    if ($existingUser) {{
        Write-Log "User {username} already exists - updating password" "WARNING"
        $securePassword = ConvertTo-SecureString "{password}" -AsPlainText -Force
        Set-LocalUser -Name "{username}" -Password $securePassword
    }} else {{
        # Create new user
        $securePassword = ConvertTo-SecureString "{password}" -AsPlainText -Force
        
        $userParams = @{{
            Name = "{username}"
            Password = $securePassword
            PasswordNeverExpires = ${pwd_never_expires}
            UserMayNotChangePassword = ${cannot_change_pwd}
            AccountNeverExpires = $true
            Disabled = ${disabled}
        }}
        
        {full_name_param}
        {description_param}
        
        New-LocalUser @userParams
        Write-Log "User {username} created successfully" "SUCCESS"
    }}
    
    # Add to Administrators group if specified
    {admin_section}
    
    # Set password must change at next logon if required
    {pwd_change_section}
    
}} catch {{
    Write-Log "Error creating user {username}: $_" "ERROR"
}}

"#,
            username = user.username,
            password = user.password,
            pwd_never_expires = if user.password_never_expires {
                "$true"
            } else {
                "$false"
            },
            cannot_change_pwd = if user.user_cannot_change_password {
                "$true"
            } else {
                "$false"
            },
            disabled = if user.account_disabled {
                "$true"
            } else {
                "$false"
            },
            full_name_param = if full_name.is_empty() {
                String::new()
            } else {
                format!(
                    "$userParams['FullName'] = \"{}\"",
                    user.full_name.as_ref().unwrap()
                )
            },
            description_param = if description.is_empty() {
                String::new()
            } else {
                format!(
                    "$userParams['Description'] = \"{}\"",
                    user.description.as_ref().unwrap()
                )
            },
            admin_section = if user.is_admin {
                format!(
                    r#"# Add to Administrators group
    try {{
        Add-LocalGroupMember -Group "Administrators" -Member "{}" -ErrorAction SilentlyContinue
        Write-Log "Added {} to Administrators group" "SUCCESS"
    }} catch {{
        Write-Log "User {} may already be in Administrators group" "WARNING"
    }}"#,
                    user.username, user.username, user.username
                )
            } else {
                "# Not adding to Administrators group".to_string()
            },
            pwd_change_section = if user.require_password_change {
                format!(
                    r#"# Force password change at next logon
    try {{
        $user = [ADSI]"WinNT://$env:COMPUTERNAME/{},User"
        $user.PasswordExpired = 1
        $user.SetInfo()
        Write-Log "Password change required for {} at next logon" "SUCCESS"
    }} catch {{
        Write-Log "Could not set password change requirement: $_" "WARNING"
    }}"#,
                    user.username, user.username
                )
            } else {
                "# No password change required".to_string()
            }
        )
    }

    /// Generate a simple single-user creation command
    pub fn generate_simple_command(user: &UserAccountConfig) -> String {
        let mut cmd = format!(
            "New-LocalUser -Name '{}' -Password (ConvertTo-SecureString '{}' -AsPlainText -Force)",
            user.username, user.password
        );

        if user.password_never_expires {
            cmd.push_str(" -PasswordNeverExpires");
        }

        if user.user_cannot_change_password {
            cmd.push_str(" -UserMayNotChangePassword");
        }

        if let Some(ref full_name) = user.full_name {
            cmd.push_str(&format!(" -FullName '{}'", full_name));
        }

        if user.is_admin {
            cmd.push_str(&format!(
                "; Add-LocalGroupMember -Group 'Administrators' -Member '{}'",
                user.username
            ));
        }

        cmd
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_user_script() {
        let config = UsersConfig {
            users: vec![
                UserAccountConfig {
                    username: "Admin".to_string(),
                    password: "P@ssw0rd".to_string(),
                    full_name: Some("Local Administrator".to_string()),
                    is_admin: true,
                    password_never_expires: true,
                    ..Default::default()
                },
                UserAccountConfig {
                    username: "TestUser".to_string(),
                    password: "Test123".to_string(),
                    is_admin: false,
                    ..Default::default()
                },
            ],
            ..Default::default()
        };

        let script = UserCreatorGenerator::generate_script(&config).unwrap();

        assert!(script.contains("Admin"));
        assert!(script.contains("TestUser"));
        assert!(script.contains("New-LocalUser"));
        assert!(script.contains("Administrators"));
    }

    #[test]
    fn test_generate_simple_command() {
        let user = UserAccountConfig {
            username: "Admin".to_string(),
            password: "secret".to_string(),
            is_admin: true,
            ..Default::default()
        };

        let cmd = UserCreatorGenerator::generate_simple_command(&user);

        assert!(cmd.contains("New-LocalUser"));
        assert!(cmd.contains("Admin"));
        assert!(cmd.contains("Administrators"));
    }
}
