use crate::core::errors::BitOSDTResult;
use serde::{Deserialize, Serialize};
use tracing::info;

/// Windows Update script generator
pub struct WindowsUpdateGenerator;

/// Windows Update configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WindowsUpdateConfig {
    /// Enable Windows Update after installation
    pub enabled: bool,
    /// Include driver updates
    pub include_drivers: bool,
    /// Include optional updates
    pub include_optional: bool,
    /// Specific KB articles to install (empty = all available)
    pub specific_kbs: Vec<String>,
    /// Timeout in minutes
    pub timeout_minutes: u32,
    /// Maximum number of update cycles
    pub max_cycles: u32,
    /// Reboot behavior
    pub reboot_behavior: RebootBehavior,
    /// Log file path
    pub log_path: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum RebootBehavior {
    /// Reboot automatically when needed
    AutoReboot,
    /// Suppress reboots (may leave updates pending)
    SuppressReboot,
    /// Prompt user for reboot
    PromptReboot,
}

impl Default for WindowsUpdateConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            include_drivers: true,
            include_optional: false,
            specific_kbs: Vec::new(),
            timeout_minutes: 120,
            max_cycles: 3,
            reboot_behavior: RebootBehavior::AutoReboot,
            log_path: "C:\\BitOSDT\\Logs\\windows-update.log".to_string(),
        }
    }
}

impl WindowsUpdateGenerator {
    /// Generate PowerShell script for Windows Update
    pub fn generate_script(config: &WindowsUpdateConfig) -> BitOSDTResult<String> {
        info!("Generating Windows Update script");

        if !config.enabled {
            return Ok("# Windows Update disabled by configuration\nexit 0".to_string());
        }

        let reboot_param = match config.reboot_behavior {
            RebootBehavior::AutoReboot => "-AutoReboot",
            RebootBehavior::SuppressReboot => "-IgnoreReboot",
            RebootBehavior::PromptReboot => "",
        };

        let include_drivers = if config.include_drivers {
            "$true"
        } else {
            "$false"
        };

        let specific_kbs_filter = if config.specific_kbs.is_empty() {
            String::new()
        } else {
            let kbs: Vec<String> = config
                .specific_kbs
                .iter()
                .map(|kb| {
                    if kb.to_uppercase().starts_with("KB") {
                        kb.to_uppercase()
                    } else {
                        format!("KB{}", kb)
                    }
                })
                .collect();
            format!("\n$specificKBs = @(\"{}\")", kbs.join("\", \""))
        };

        let script = format!(
            r#"# BitOSDT Windows Update Script
# Generated by BitOSDT 2.0
# ================================================

$ErrorActionPreference = "Continue"
$LogPath = "{log_path}"
$TimeoutMinutes = {timeout}
$MaxCycles = {max_cycles}
$IncludeDrivers = {include_drivers}
{specific_kbs}

# Create log directory
$logDir = Split-Path $LogPath -Parent
if (-not (Test-Path $logDir)) {{
    New-Item -Path $logDir -ItemType Directory -Force | Out-Null
}}

function Write-Log {{
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logLine = "$timestamp [$Level] $Message"
    $logLine | Out-File -Append $LogPath
    
    switch ($Level) {{
        "ERROR" {{ Write-Host $logLine -ForegroundColor Red }}
        "WARNING" {{ Write-Host $logLine -ForegroundColor Yellow }}
        "SUCCESS" {{ Write-Host $logLine -ForegroundColor Green }}
        default {{ Write-Host $logLine }}
    }}
}}

function Install-PSWindowsUpdate {{
    if (-not (Get-Module -ListAvailable -Name PSWindowsUpdate)) {{
        Write-Log "Installing PSWindowsUpdate module..."
        try {{
            Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -ErrorAction SilentlyContinue
            Install-Module -Name PSWindowsUpdate -Force -Scope AllUsers -ErrorAction Stop
            Write-Log "PSWindowsUpdate module installed successfully" "SUCCESS"
        }} catch {{
            Write-Log "Failed to install PSWindowsUpdate: $_" "ERROR"
            return $false
        }}
    }}
    return $true
}}

function Get-AvailableUpdates {{
    Write-Log "Checking for available updates..."
    
    try {{
        Import-Module PSWindowsUpdate -Force
        
        $params = @{{
            MicrosoftUpdate = $true
            NotCategory = @()
        }}
        
        if (-not $IncludeDrivers) {{
            $params.NotCategory += "Drivers"
        }}
        
        $updates = Get-WindowsUpdate @params
        
        # Filter for specific KBs if specified
        if ($specificKBs -and $specificKBs.Count -gt 0) {{
            Write-Log "Filtering for specific KBs: $($specificKBs -join ', ')"
            $updates = $updates | Where-Object {{
                foreach ($kb in $specificKBs) {{
                    if ($_.KB -eq $kb -or $_.Title -match $kb) {{
                        return $true
                    }}
                }}
                return $false
            }}
        }}
        
        return $updates
    }} catch {{
        Write-Log "Error getting updates: $_" "ERROR"
        return @()
    }}
}}

function Install-Updates {{
    param([array]$Updates)
    
    if ($Updates.Count -eq 0) {{
        Write-Log "No updates to install"
        return $true
    }}
    
    Write-Log "Installing $($Updates.Count) update(s)..."
    
    try {{
        Import-Module PSWindowsUpdate -Force
        
        $installParams = @{{
            Install = $true
            AcceptAll = $true
            {reboot_param}
        }}
        
        Get-WindowsUpdate @installParams | Out-Null
        
        Write-Log "Update installation completed" "SUCCESS"
        return $true
    }} catch {{
        Write-Log "Error installing updates: $_" "ERROR"
        return $false
    }}
}}

# Main execution
Write-Log "Starting Windows Update process..."
Write-Log "Timeout: $TimeoutMinutes minutes"
Write-Log "Max cycles: $MaxCycles"
Write-Log "Include drivers: $IncludeDrivers"

# Install PSWindowsUpdate if needed
if (-not (Install-PSWindowsUpdate)) {{
    Write-Log "Cannot proceed without PSWindowsUpdate module" "ERROR"
    exit 1
}}

$startTime = Get-Date
$cycle = 0
$rebootPending = $false

while ($cycle -lt $MaxCycles) {{
    $cycle++
    Write-Log "Update cycle $cycle of $MaxCycles"
    
    # Check timeout
    $elapsed = (Get-Date) - $startTime
    if ($elapsed.TotalMinutes -ge $TimeoutMinutes) {{
        Write-Log "Timeout reached after $($elapsed.TotalMinutes) minutes" "WARNING"
        break
    }}
    
    # Get available updates
    $updates = Get-AvailableUpdates
    
    if ($updates.Count -eq 0) {{
        Write-Log "No more updates available" "SUCCESS"
        break
    }}
    
    Write-Log "Found $($updates.Count) update(s):"
    foreach ($update in $updates) {{
        Write-Log "  - $($update.Title) ($($update.KB))"
    }}
    
    # Install updates
    $success = Install-Updates -Updates $updates
    
    if (-not $success) {{
        Write-Log "Update installation failed, continuing to next cycle..." "WARNING"
    }}
    
    # Check for pending reboot
    $rebootRequired = (Get-WURebootStatus -Silent)
    if ($rebootRequired) {{
        Write-Log "Reboot required after updates"
        $rebootPending = $true
        
        # If AutoReboot, the system will reboot automatically
        # Otherwise, continue for SuppressReboot or break for PromptReboot
        {reboot_handling}
    }}
}}

# Final status
Write-Log "Windows Update process completed"
Write-Log "Total cycles: $cycle"
Write-Log "Total time: $((Get-Date) - $startTime)"

if ($rebootPending) {{
    Write-Log "A reboot is pending to complete updates" "WARNING"
    exit 3010  # ERROR_SUCCESS_REBOOT_REQUIRED
}} else {{
    exit 0
}}
"#,
            log_path = config.log_path,
            timeout = config.timeout_minutes,
            max_cycles = config.max_cycles,
            include_drivers = include_drivers,
            specific_kbs = specific_kbs_filter,
            reboot_param = reboot_param,
            reboot_handling = match config.reboot_behavior {
                RebootBehavior::AutoReboot => "# AutoReboot - PSWindowsUpdate handles this",
                RebootBehavior::SuppressReboot => {
                    "Write-Log \"Reboot suppressed by configuration\" \"WARNING\""
                }
                RebootBehavior::PromptReboot =>
                    r#"
        $response = Read-Host "Reboot now? (Y/N)"
        if ($response -eq 'Y') {
            Write-Log "User requested reboot"
            Restart-Computer -Force
        }"#,
            }
        );

        Ok(script)
    }

    /// Generate a simple update command without PSWindowsUpdate module
    pub fn generate_simple_command() -> String {
        r#"# Simple Windows Update using built-in methods
$updateSession = New-Object -ComObject Microsoft.Update.Session
$updateSearcher = $updateSession.CreateUpdateSearcher()
$searchResult = $updateSearcher.Search("IsInstalled=0 and Type='Software'")

if ($searchResult.Updates.Count -gt 0) {
    Write-Host "Found $($searchResult.Updates.Count) update(s)"
    
    $updatesToInstall = New-Object -ComObject Microsoft.Update.UpdateColl
    foreach ($update in $searchResult.Updates) {
        $updatesToInstall.Add($update) | Out-Null
    }
    
    $installer = $updateSession.CreateUpdateInstaller()
    $installer.Updates = $updatesToInstall
    $installResult = $installer.Install()
    
    Write-Host "Installation result: $($installResult.ResultCode)"
} else {
    Write-Host "No updates available"
}"#
        .to_string()
    }

    /// Generate command to check for pending reboot
    pub fn generate_reboot_check() -> String {
        r#"# Check for pending reboot
$rebootRequired = $false

# Check Windows Update
$wuReboot = Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired"

# Check Component Based Servicing
$cbsReboot = Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending"

# Check PendingFileRenameOperations
$fileRenameReboot = (Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager" -Name PendingFileRenameOperations -ErrorAction SilentlyContinue) -ne $null

$rebootRequired = $wuReboot -or $cbsReboot -or $fileRenameReboot

if ($rebootRequired) {
    Write-Host "Reboot is pending"
    exit 1
} else {
    Write-Host "No reboot pending"
    exit 0
}"#
        .to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_update_script() {
        let config = WindowsUpdateConfig::default();
        let script = WindowsUpdateGenerator::generate_script(&config).unwrap();

        assert!(script.contains("PSWindowsUpdate"));
        assert!(script.contains("Get-WindowsUpdate"));
        assert!(script.contains("Install"));
    }

    #[test]
    fn test_disabled_config() {
        let config = WindowsUpdateConfig {
            enabled: false,
            ..Default::default()
        };

        let script = WindowsUpdateGenerator::generate_script(&config).unwrap();
        assert!(script.contains("disabled"));
    }

    #[test]
    fn test_specific_kbs() {
        let config = WindowsUpdateConfig {
            specific_kbs: vec!["KB5034441".to_string(), "5034442".to_string()],
            ..Default::default()
        };

        let script = WindowsUpdateGenerator::generate_script(&config).unwrap();
        assert!(script.contains("KB5034441"));
        assert!(script.contains("KB5034442"));
    }
}
