import { OobeProfileRequest } from "./oobeTypes";

export function createDefaultOobeProfileRequest(): OobeProfileRequest {
  return {
    name: "",
    description: "",
    overwrite: false,
    triggerMode: "FirstLogonUsbScan",
    oobeConfig: {
      skipMachineOobe: true,
      skipUserOobe: true,
      hideEula: true,
      hidePrivacySettings: true,
      hideWirelessSetup: true,
      hideLocalAccountScreen: false,
      hideOnlineAccountScreens: true,
      networkLocation: "Work",
      protectYourPc: "Recommended",
      computerName: "",
    },
    domainJoin: {
      enabled: false,
      domain: "",
      username: "",
      password: "",
      ouPath: "",
    },
    domainJoinMode: "SpecializeXml",
    promptForComputerName: true,
    defaultUser: {
      enabled: false,
      username: "",
      password: "",
      group: "Administrators",
    },
    wifi: {
      enabled: false,
      ssid: "",
      password: "",
      authentication: "Wpa2Psk",
      encryption: "Aes",
      autoConnect: true,
      hiddenNetwork: false,
      dnsServer1: "",
      dnsServer2: "",
    },
    apps: {
      wingetPackages: [],
      chocolateyPackages: [],
      customInstallers: [],
      copiedItems: [],
      copyDestination: "",
      disableBitLocker: false,
      rebootAfterDisableBitLocker: false,
      autoInstallChocolatey: true,
      continueOnError: true,
      enableCustomScripts: false,
      customScripts: [],
    },
    language: "en-US",
    inputLocale: "0409:00000409",
    timezone: "Pacific Standard Time",
    enableDebloat: false,
    debloatScriptContent: "",
  };
}
